### ISSUE TITLE
Online Shiny app unavailable

### ISSUE THREAD

**Issue by baezortega** [USCbiostats/iMutSig#1]
Hello,

I'm writing because I haven't been able to access the online version of iMutSig (https://zhiyang.shinyapps.io/imutsig/) for the last two days. The website shows this message:

`ERROR: An error has occurred. Check your logs or contact the app author for clarification.`

I was wondering if maybe @zhiiiyang could please look into this when possible?

Many thanks,
Adrian

**Comment by zhiiiyang** [comment]
Hi Adrian, thank you for letting me know. I will take a look at it and get back to me later today.

**Comment by zhiiiyang** [comment]
@baezortega, the website is updated now. Please let me know if it works.

**Comment by baezortega** [comment]
Hi Zhi, it seems to be working fine now, many thanks!
Adrian
