### ISSUE TITLE
bugs in README file

### ISSUE THREAD

**Issue by ksiegmund** [USCbiostats/iMutSig#2]
@zhiiiyang I think your readme needs !() in these 2 statements.

if (!("pmsignature" %in% rownames(installed.packages()))){
  devtools::install_github("friend1ws/pmsignature", ref = "devel")
}

if (!("decompTumor2Sig" %in% rownames(installed.packages()))){
  devtools::install_github("zhiiiyang/decompTumor2Sig")
}

**Comment by zhiiiyang** [comment]
@ksiegmund thank you for pointing it out. I have updated the readme on the master branch. Also, `d3heatmap` is not on CRAN yet so I changed the installation instruction for it.
